print("Hello, my name is Andrew")
print ("I have brown hair and blue eyes")
print ("I am 155.5cm tall")
print ("I am 30 years old")
print ("My favorite number is 21")
print ("My favorite hobby is the electric guitar")
print ("I live with my Mother, Father, and Sister")
print ("Pets? yes, two cats")
print ("my hometown is Port Hawkesbury")
print ("I have lived in Dartmouth, Fredericton, and Whycocomagh")
print ("I have had four years of post-secondary before this")
print ("I sent 7.5 years working in the media industry")
